/*
Copyright © 2015 Intel Corporation
This program and the accompanying materials are made available under the terms of the Eclipse Public License v1.0, 
 which accompanies this distribution, and is available at http://www.eclipse.org/legal/epl-v10.html . https://github.com/viqet
* Contributors:
*    Intel Corporation - initial API and implementation and/or initial documentation
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViqetDesktop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViqetDesktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VQEG Image Quality Evaluation Tool (VIQET) is a free and open source tool for evaluating quality of consumer photos. VIQET is easy to use and based on objective no-reference image quality evaluation methods. More information about VQEG projects is available at www.vqeg.org.
        /// </summary>
        public static string AboutPageText {
            get {
                return ResourceManager.GetString("AboutPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze.
        /// </summary>
        public static string Analyze {
            get {
                return ResourceManager.GetString("Analyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download our Android app and enjoy instant analysis of your photos without the hassle of syncing your photos to your PC!.
        /// </summary>
        public static string AndroidIsAvailableToo {
            get {
                return ResourceManager.GetString("AndroidIsAvailableToo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to home page.
        /// </summary>
        public static string BackToMainScreenWarning {
            get {
                return ResourceManager.GetString("BackToMainScreenWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string BreadCrumb1 {
            get {
                return ResourceManager.GetString("BreadCrumb1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string BreadCrumb2 {
            get {
                return ResourceManager.GetString("BreadCrumb2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string BreadCrumb3 {
            get {
                return ResourceManager.GetString("BreadCrumb3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string BreadCrumb4 {
            get {
                return ResourceManager.GetString("BreadCrumb4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string BreadCrumbTitle1 {
            get {
                return ResourceManager.GetString("BreadCrumbTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Photos.
        /// </summary>
        public static string BreadCrumbTitle2 {
            get {
                return ResourceManager.GetString("BreadCrumbTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string BreadCrumbTitle3 {
            get {
                return ResourceManager.GetString("BreadCrumbTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string BreadCrumbTitle4 {
            get {
                return ResourceManager.GetString("BreadCrumbTitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to read more.
        /// </summary>
        public static string ClickToReadMore {
            get {
                return ResourceManager.GetString("ClickToReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse Visualization.
        /// </summary>
        public static string CollapsePhotos {
            get {
                return ResourceManager.GetString("CollapsePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Test Name Here.
        /// </summary>
        public static string DefaultTestName {
            get {
                return ResourceManager.GetString("DefaultTestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Multiple Items.
        /// </summary>
        public static string DeleteMultipleItems {
            get {
                return ResourceManager.GetString("DeleteMultipleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove these photos from the test?.
        /// </summary>
        public static string DeletePhotosConfirmationMessage {
            get {
                return ResourceManager.GetString("DeletePhotosConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteSelected {
            get {
                return ResourceManager.GetString("DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanently delete these tests?.
        /// </summary>
        public static string DeleteTestsConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteTestsConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed Results.
        /// </summary>
        public static string DetailedResults {
            get {
                return ResourceManager.GetString("DetailedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you know?.
        /// </summary>
        public static string DidYouKnow {
            get {
                return ResourceManager.GetString("DidYouKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display individual photo MOS.
        /// </summary>
        public static string DisplayPhotoMOS {
            get {
                return ResourceManager.GetString("DisplayPhotoMOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Current Test.
        /// </summary>
        public static string EditCurrentTest {
            get {
                return ResourceManager.GetString("EditCurrentTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditSelected {
            get {
                return ResourceManager.GetString("EditSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for minimum number of photos.
        /// </summary>
        public static string EnforceMethodology {
            get {
                return ResourceManager.GetString("EnforceMethodology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Details:.
        /// </summary>
        public static string ExceptionDetails {
            get {
                return ResourceManager.GetString("ExceptionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to go back to the main screen? Any changes made to this test will be lost.
        /// </summary>
        public static string ExitSelectPhotosWarning {
            get {
                return ResourceManager.GetString("ExitSelectPhotosWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand Visualization.
        /// </summary>
        public static string ExpandPhotos {
            get {
                return ResourceManager.GetString("ExpandPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as.
        /// </summary>
        public static string ExportAsLabel {
            get {
                return ResourceManager.GetString("ExportAsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as CSV.
        /// </summary>
        public static string ExportCSV {
            get {
                return ResourceManager.GetString("ExportCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as PDF.
        /// </summary>
        public static string ExportPDF {
            get {
                return ResourceManager.GetString("ExportPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as XML.
        /// </summary>
        public static string ExportXML {
            get {
                return ResourceManager.GetString("ExportXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIQET was not able to identify flat regions in some test photos. This may be because those test photos do not follow VIQET methodology or might have high noise. .
        /// </summary>
        public static string FlatRegionError {
            get {
                return ResourceManager.GetString("FlatRegionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidelines.
        /// </summary>
        public static string GeneralGuidelines {
            get {
                return ResourceManager.GetString("GeneralGuidelines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeButton {
            get {
                return ResourceManager.GetString("HomeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string ImageDetails {
            get {
                return ResourceManager.GetString("ImageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import More Photos.
        /// </summary>
        public static string ImportMorePhotos {
            get {
                return ResourceManager.GetString("ImportMorePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Photos.
        /// </summary>
        public static string ImportPhotos {
            get {
                return ResourceManager.GetString("ImportPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a test name.
        /// </summary>
        public static string IncorrectName {
            get {
                return ResourceManager.GetString("IncorrectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methodology not followed.
        /// </summary>
        public static string MethodologyNotFollowed {
            get {
                return ResourceManager.GetString("MethodologyNotFollowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Info.
        /// </summary>
        public static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOS.
        /// </summary>
        public static string MOS {
            get {
                return ResourceManager.GetString("MOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean Opinion Scores.
        /// </summary>
        public static string MOSAbbr {
            get {
                return ResourceManager.GetString("MOSAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Test.
        /// </summary>
        public static string NewTest {
            get {
                return ResourceManager.GetString("NewTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add photos.
        /// </summary>
        public static string NoPhotosSelected {
            get {
                return ResourceManager.GetString("NoPhotosSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 5 photos in each input category are required to calculate overall scores.
        /// </summary>
        public static string NoteAboutMinPhotos {
            get {
                return ResourceManager.GetString("NoteAboutMinPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 5 photos in each input category are required to calculate category scores.
        /// </summary>
        public static string NoteAboutMinPhotosCategory {
            get {
                return ResourceManager.GetString("NoteAboutMinPhotosCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenSelected {
            get {
                return ResourceManager.GetString("OpenSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string OutputCategory {
            get {
                return ResourceManager.GetString("OutputCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string OverallInfo {
            get {
                return ResourceManager.GetString("OverallInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall.
        /// </summary>
        public static string OverallMOS {
            get {
                return ResourceManager.GetString("OverallMOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Count.
        /// </summary>
        public static string PhotoCount {
            get {
                return ResourceManager.GetString("PhotoCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Backend DLL threw an exception while processing photo.
        /// </summary>
        public static string PhotoProcessingError {
            get {
                return ResourceManager.GetString("PhotoProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Photo.
        /// </summary>
        public static string ProcessingPhoto {
            get {
                return ResourceManager.GetString("ProcessingPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VQEG Image Quality Evaluation Tool (VIQET).
        /// </summary>
        public static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIQET.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro Mode.
        /// </summary>
        public static string ProMode {
            get {
                return ResourceManager.GetString("ProMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Result has been deleted.
        /// </summary>
        public static string ResultDeletedError {
            get {
                return ResourceManager.GetString("ResultDeletedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result you clicked has been deleted by another instance of the application. Click OK to refresh this window..
        /// </summary>
        public static string ResultDoesntExistError {
            get {
                return ResourceManager.GetString("ResultDoesntExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Mean Opinion Scores (MOS) +/- Standard Error.
        /// </summary>
        public static string ResultPageOverallHeader {
            get {
                return ResourceManager.GetString("ResultPageOverallHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping.
        /// </summary>
        public static string Stopping {
            get {
                return ResourceManager.GetString("Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Score.
        /// </summary>
        public static string SubmitScore {
            get {
                return ResourceManager.GetString("SubmitScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Name.
        /// </summary>
        public static string TestName {
            get {
                return ResourceManager.GetString("TestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Backend DLL threw an exception while fetching version info.
        /// </summary>
        public static string VersionFetchError {
            get {
                return ResourceManager.GetString("VersionFetchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Release.
        /// </summary>
        public static string VersionName {
            get {
                return ResourceManager.GetString("VersionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualization.
        /// </summary>
        public static string Visualization {
            get {
                return ResourceManager.GetString("Visualization", resourceCulture);
            }
        }
    }
}
